github action update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,8 +45,15 @@ jobs:
         ls -l backend/
         ls -l
 
+    - name: Validate SSH key
+      run: |
+        if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
+          echo "Error: EC2_SSH_KEY is not set."
+          exit 1
+        fi
+
     - name: Copy WAR and Dockerfile to EC2
-      uses: appleboy/scp-action@v0.1.7
+      uses: appleboy/scp-action@v0.1.8
       with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USER }}
